# config/config.yaml (BASE CONFIGURATION)

# These settings are shared between CPU and GPU
training:
  buffer_size: 75000
  batch_size: 128
  tau: 0.005
  gamma: 0.99
  learning_starts: 10000 
  
  walk_forward:
    n_splits: 5
    min_train_size: 40000
    test_size: 30000
    timesteps_per_split: 150000

  fine_tuning:
    recent_data_years: 2.5
    total_timesteps: 200000
    learning_rate: 0.00001

environment:
  initial_balance: 10000
  sequence_length: 60
  commission_pct: 0.0005
  turnover_penalty: 0.001

model:
  features_dim: 256
  cnn_out_channels: 64
  transformer_n_heads: 4
  transformer_n_layers: 2
  transformer_dropout: 0.1